name: Terraform Workflow - Delete

on:
  workflow_dispatch:  # Manually trigger the workflow
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: farmhost.in  # or your self-hosted runner label

    # Define environment variables for the whole job
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.5
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy

