name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: farmhost.in  # or your self-hosted runner label

    # Define environment variables for the whole job
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init
      env:
        TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
